-- MySQL Script generated by MySQL Workbench
-- Чт 19 янв 2023 08:13:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ObjectNumber_ObjectName`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ObjectNumber_ObjectName` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ObjectNumber` VARCHAR(45) NOT NULL,
  `ObjectName` VARCHAR(200) NOT NULL,
  `ObjectLocation` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Objectnumber_UNIQUE` (`ObjectNumber` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Номер объекта, название объекта.';


-- -----------------------------------------------------
-- Table `mydb`.`ObjectNumber_BoreNumber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ObjectNumber_BoreNumber` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Objectnumber` VARCHAR(45) NOT NULL,
  `BoreNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `Objectnumber_UNIQUE` (`Objectnumber` ASC) VISIBLE,
  CONSTRAINT `fk_Objectnumber_Borenumber_1`
    FOREIGN KEY (`Objectnumber`)
    REFERENCES `mydb`.`ObjectNumber_ObjectName` (`ObjectNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Номер объекта, номер скважины.';


-- -----------------------------------------------------
-- Table `mydb`.`BoreNumber_LayerRoof_LayerBase_LayerDescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BoreNumber_LayerRoof_LayerBase_LayerDescription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `BoreNumber` VARCHAR(45) NOT NULL,
  `LayerRoof` FLOAT NOT NULL,
  `LayerBase` FLOAT NOT NULL,
  `LayerDescription` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_BoreNumber_LayerRoof_LayerBase_LayerDescription_1_idx` (`BoreNumber` ASC) VISIBLE,
  CONSTRAINT `fk_BoreNumber_LayerRoof_LayerBase_LayerDescription_1`
    FOREIGN KEY (`BoreNumber`)
    REFERENCES `mydb`.`ObjectNumber_ObjectName` (`ObjectNumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Номер скважины, кровля слоя, подошва слоя, описание слоя.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
